### ISSUE TITLE
Version 0.3.5 gives similar error as 0.3.1 did 

### ISSUE THREAD

**Issue by ppatel23** [ngzhian/pycrunchbase#22]
I downloaded the latest version 0.3.5 (using pip install) and I still get the very same error -

cb = pycrunchbase.CrunchBase(API_KEY)
cb.organization('github')

Traceback (most recent call last):
File "", line 1, in 
File "/Users/Pinkesh/anaconda/lib/python2.7/site-packages/pycrunchbase/pycrunchbase.py", line 51, in organization
return Organization(node_data) if node_data else None
File "/Users/Pinkesh/anaconda/lib/python2.7/site-packages/pycrunchbase/resource/node.py", line 20, in init
self.parse_relationship()
File "/Users/Pinkesh/anaconda/lib/python2.7/site-packages/pycrunchbase/resource/node.py", line 48, in parse_relationship
self, rs_name, Relationship(rs_name, rs_dict.get(rs_name)))
File "/Users/Pinkesh/anaconda/lib/python2.7/site-packages/pycrunchbase/resource/relationship.py", line 35, in __init
self.buildPageItem(data.get('item'))
File "/Users/Pinkesh/anaconda/lib/python2.7/site-packages/pycrunchbase/resource/relationship.py", line 60, in buildPageItem
for prop in node.KNOWN_PROPERTIES:
AttributeError: 'PageItem' object has no attribute 'KNOWN_PROPERTIES'

**Comment by ngzhian** [comment]
@ppatel23 thanks for the report! I have commited a fix, this is on v0.3.6, I've tried it and it works fine. Hope it will work for you too. Let me know if there are any more issues. Otherwise if it works you may close this issue, thanks :)

**Comment by ngzhian** [comment]
It's been a while, so I assume this is fixed
