### ISSUE TITLE
Error with Crunchbase API wrapper pycrunchbase

### ISSUE THREAD

**Issue by i25959341** [ngzhian/pycrunchbase#7]
I tried importing the pycrunchbase api wrapper and i get the following error.

>> from pycrunchbase import *

Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    from pycrunchbase import *
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pycrunchbase/__init__.py", line 1, in <module>
    from .pycrunchbase import (
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pycrunchbase/pycrunchbase.py", line 4, in <module>
    from .resource import (
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pycrunchbase/resource/__init__.py", line 1, in <module>
    from .acquisition import Acquisition
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pycrunchbase/resource/acquisition.py", line 3, in <module>
    from .node import Node
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pycrunchbase/resource/node.py", line 3, in <module>
    from .relationship import NoneRelationshipSingleton, Relationship
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pycrunchbase/resource/relationship.py", line 3, in <module>
    from .page import Page
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pycrunchbase/resource/page.py", line 4, in <module>
    from .pageitem import PageItem
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pycrunchbase/resource/pageitem.py", line 58, in <module>
    @six.python_2_unicode_compatible
AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'

**Comment by ngzhian** [comment]
Hi, that seems to be an issue with dependency, pycrunchbase requires [`six==1.9.0`](https://pypi.python.org/pypi/six/). Can you please check that the your installation has the necessary version. It might be possible that some other version of `six` is installed in `site-packages`.

**Comment by i25959341** [comment]
Hi, how do I check the version of the six?

**Comment by ngzhian** [comment]
are you doing this from the python shell? you can try this
```
>>> import six
>>> six.__version__
'1.9.0'

if you are in the terminal, try this:
```
$ pip freeze
six==1.9.0
```
In both cases you should see `six`'s version as `1.9.0`.

**Comment by i25959341** [comment]
Hey, you are right, it is 1.4.1 

I tried using pip to upgrade six, but it keep saying it is installed already, is there other to install it? like Brew?

**Comment by i25959341** [comment]
Hi on my python shells it says 1.4.1, but on my pip it says 1.9?? Do I have force it use the 1.9 version?

**Comment by ngzhian** [comment]
Hm, try `pip install --upgrade six`?
Or maybe `pip

**Comment by i25959341** [comment]
mmmm still have trouble, let me stackoverflow this lol

**Comment by i25959341** [comment]
Thanks a lot for the help!

**Comment by ngzhian** [comment]
strange, probably something to do with virtualenv? best of luck in figuring this out! let me know if I can help in any other ways.
Also if you don't mind, post your solution here after you figure it out, good for anyone who encounters a similar issue :)

**Comment by i25959341** [comment]
ahh not using virtualenv, but yes of cos

**Comment by i25959341** [comment]
Hi, I just manually installed Six again instead of using pip, by downloading the file and  using python install setup

**Comment by ngzhian** [comment]
Cool, glad it worked! (tip: use virtualenv :P)

**Comment by i25959341** [comment]
haha yes, will do :)
